services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - automobile

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: automobile
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "3502:5432"
    volumes:
      - automobile_data:/var/lib/postgresql/data
    networks:
      - automobile

networks:
  automobile:
    driver: bridge

volumes:
  automobile_data:
